# Generated by Django 4.2.2 on 2023-07-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=10000)),
                ('date_needed', models.DateField()),
                ('Request', models.CharField(max_length=100000)),
                ('payment_reciept', models.ImageField(upload_to='payment_slip/')),
            ],
        ),
    ]
