# Generated by Django 4.2.2 on 2023-07-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Request',
            new_name='request',
        ),
    ]
